-- dictionary-tables
create table Degree
(
    id   int generated by default as identity primary key,
    name varchar not null
);

create table LessonType
(
    id       int generated by default as identity primary key,
    typeName varchar not null
);

-- main tables
create table Subject
(
    id                      int generated by default as identity primary key,
    description             varchar not null,
    laboratoryAcademicHours int,
    practicalAcademicHours  int,
    lectureAcademicHours    int     not null,
    courseAcademicHours     int
);

create table Teacher
(
    id         int generated by default as identity primary key,
    surname    varchar(100)               not null,
    name       varchar(100)               not null,
    patronymic varchar(100),
    degree     int references Degree (id) not null
);

create table StudentGroup
(
    id   int generated by default as identity primary key,
    name varchar(50) not null
);

create table Lesson
(
    id           int generated by default as identity primary key,
    lessonTypeId int references LessonType (id) not null,
    timeDate     Date                           not null,
    subjectId    int references Subject (id)    not null
);

create table Student
(
    id             int primary key,
    surname        varchar(100)                     not null,
    name           varchar(100)                     not null,
    patronymic     varchar(100),
    studentGroupId int references StudentGroup (id) not null
);

-- many-to-many tables
create table LessonForStudentGroup
(
    studentGroupId int references StudentGroup (id) not null,
    lessonId       int references Student (id)      not null
);

create table TeacherInGroup
(
    studentGroupId int references StudentGroup (id) not null,
    teacherId      int references Teacher (id)      not null
);

create table SubjectForTeacher
(
    subjectId int references Subject (id) not null,
    teacherId int references Teacher (id) not null
);